using System.ComponentModel.DataAnnotations;

namespace ASK.Group.Api.Models;

public class OperationsException
{
    public int Id { get; set; }

    [Required, MaxLength(50)]
    public string ExceptionNumber { get; set; } = string.Empty;

    [Required, MaxLength(100)]
    public string ExceptionType { get; set; } = string.Empty;

    [Required, MaxLength(30)]
    public string Severity { get; set; } = "Medium";

    [Required, MaxLength(30)]
    public string Status { get; set; } = "Open";

    [MaxLength(100)]
    public string? ReferenceType { get; set; }

    [MaxLength(100)]
    public string? ReferenceNumber { get; set; }

    [MaxLength(100)]
    public string? Department { get; set; }

    [MaxLength(100)]
    public string? AssignedDepartment { get; set; }

    [MaxLength(200)]
    public string? Title { get; set; }

    [MaxLength(2000)]
    public string? Description { get; set; }

    public int? BookingId { get; set; }
    public Booking? Booking { get; set; }

    public int? ShipmentId { get; set; }
    public Shipment? Shipment { get; set; }

    public int? TripId { get; set; }
    public TransportTrip? Trip { get; set; }

    public int? DriverId { get; set; }
    public Driver? Driver { get; set; }

    public int? VehicleId { get; set; }
    public Vehicle? Vehicle { get; set; }

    public int? AssignedToUserId { get; set; }
    public AppUser? AssignedToUser { get; set; }

    public int EscalationLevel { get; set; }

    public DateTime DetectedAt { get; set; } = DateTime.UtcNow;

    public DateTime? DueAt { get; set; }

    public DateTime? LastEscalatedAt { get; set; }

    public DateTime? AcknowledgedAt { get; set; }

    public int? AcknowledgedByUserId { get; set; }

    public DateTime? ResolvedAt { get; set; }

    public int? ResolvedByUserId { get; set; }

    [MaxLength(2000)]
    public string? Resolution { get; set; }

    [MaxLength(2000)]
    public string? ResolutionNotes { get; set; }

    public bool IsAutoGenerated { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime? UpdatedAt { get; set; }
}
